version: '3.2'
services:
  app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./:/app
    command: ["bin/console", "twitch", "${TWITCH_CHANNEL}", "-vv"]
  db:
    image: redis:6-bullseye