version: '3.2'
services:
  app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./:/app
    environment:
      TWITCH_CHANNEL: strawburrypokki
    command: ["bin/console", "twitch", "-vv", "--colors", "--welcome"]
  db:
    image: redis:6-bullseye